### ISSUE TITLE
[RFC] Discuss SQL-like specification for Metable.

### ISSUE THREAD

**Issue by jovany-wang** [jovany-wang/metable#4]
TO BE EDIT.

**Comment by meijies** [comment]
## Support SQL
The sql statement is the most common way of interacting with database and metable is planning to support it. so, let's discuss which sql statements need to be support?

###  Support DDL Statement.

```  SQL
create database <database_name>;

drop database <database_name>;

create table <table_name> (
    (<column_name>, <column_type, <column_option>),
    (,<column_name>, <column_type>, <column_option>)*,
    primary key <column_name> (, <column_name>)*
) <table_option>;

drop table <table_name>;
```
### Support DML Statement.

``` SQL
(insert|pub) into <table_name>(<column_name> (, <column_name>)*)) values (<value> (,<value>)*){1, n};

delete from <table_name> where <condition> (and|or [condition])*;

(select | sub ) (*| <column_name > (as alias)?){1,n} from <table_name > where <condition> (and|or [condition])*;
```

### pub and sub

the another way to support pub and sub is use exists insert and query sql with a pub or sub action, so  we don't need to invent pub and sub sql statement, but how we can support it at command client ?  just ``` sub select * from student``` ?

**Comment by meijies** [comment]
## Support SQL
The sql statement is the most common way of interacting with database and metable is planning to support it. so, let's discuss which sql statements need to be support?

###  Support DDL Statement.

```  SQL
create database <database_name>;

drop database <database_name>;

create table <table_name> (
    (<column_name>, <column_type, <column_option>),
    (,<column_name>, <column_type>, <column_option>)*,
    primary key <column_name> (, <column_name>)*
) <table_option>;

drop table <table_name>;
```
### Support DML Statement.

``` SQL
(insert|pub) into <table_name>(<column_name> (, <column_name>)*)) values (<value> (,<value>)*){1, n};

delete from <table_name> where <condition> (and|or [condition])*;

(select | sub ) (*| <column_name > (as alias)?){1,n} from <table_name > where <condition> (and|or [condition])*;
```

### pub and sub

the another way to support pub and sub is use exists insert and query sql with a pub or sub action, so  we don't need to invent pub and sub sql statement, but how we can support it at command client ?  just ``` sub select * from student``` ?

**Comment by jovany-wang** [comment]
> (select | sub ) (*| <column_name > (as alias)?){1,n} from <table_name > where <condition> (and|or [condition])*;

Just wondering that how we define the subscribe callback?

**Comment by meijies** [comment]
> > (select | sub ) (_| <column_name > (as alias)?){1,n} from <table_name > where  (and|or [condition])_;
> 
> Just wondering that how we define the subscribe callback?

the select statement is enough to represent what data do you want, and let "action"(select/pub) representing the way you fetch data. client may use select to pull all data to consume or client react the data push from metable server by sub.  user need to specify a function to determine how to consume the data, this can be achieved by lambda,function pointer, or interface .  so, the api may look like as blew.

``` c++
client.sql("select * from table").sub(handler);

client.sql("select * from table").query();
```

**Comment by jovany-wang** [comment]
@meijies Yes. I totally understand that it could be finished by lambda or any callback functions in programming languages(including C++/Java/Go, etc). But what I'm wondering is **How it works in sql command**.

**Comment by jovany-wang** [comment]
```sql
> sub (name, age) from student_table with (name, age) -> {print("name={}, age={}", name, age)}
                                           |________________________________________________|
                                                                this is the callback
```

**Comment by meijies** [comment]
> How about this
> 
> ```sql
> > sub (name, age) from student_table with (name, age) -> {print("name={}, age={}", name, age)}
>                                            |________________________________________________|
>                                                                 this is the callback
> ```
> 
> And once there is new record for student_table, the callback will be invoked and print the info.

for command case, if user just need to print the data with different format. I perfer allow user set a print format(such as csv, table and so on). we just support these formats. if user need to support more case for sub action. let's dussion futher more.

**Comment by meijies** [comment]
> Further more, we can also support the interactions between Metable SQL and other programming languages like Python:
> 
> ```sql
> """py
> def f(name, age):
>     # do sth
> """
> 
> sub (name, age) from student_table with py.func("f")
> ```

personally, I think it's better to use python client, shell command or udf  to achieve this.

**Comment by jovany-wang** [comment]
@meijies OK.

**Comment by meijies** [comment]
@jovany-wang OK

**Comment by jovany-wang** [comment]
Let's close this one, and open another one to trace the work items on implementations.
